productos = {
  productos = {
  "MONDELEZ OREO D.R. 118GR 3U 354G PQ AGR": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201735258",},
  "BAGLEY SONRISAS FRAM DL RELLE 108GR PACK X3 U 324 G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SONRISAS", "ean": "7790040133471",},
  "MONDELEZ OREO D.R. 118GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201735296",},
  "BAGLEY SONRISAS DR 108 GRS PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SONRISAS", "ean": "7790040133488",},
  "MONDELEZ TERRABUSI MELBA DUL.RELLE. 120 GRPAQUETE": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MELBA", "ean": "7622300829728",},
  "LIA MACUCAS GALL DUL RELL 110GR PAQ SPL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MACUCAS", "ean": "7790040145337",},
  "TERRABUSI LINCOLN CLASICA. D.S. 3U 153GR PQ AGR 459G": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201745547",},
  "ARCOR MANA VAIN DUL.SEC. 136GR PAQ 3U 408G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040137844",},
  "MONDELEZ CEREALITA CLASICA INT 212GR PAQ 3U 636G": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CEREALITAS", "ean": "7622201745905",},
  "ARCOR HOGARENAS SALVADO CEREAL 200 G.C/U PAQ.X 3 UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040132955",},
  "MONDELEZ CEREALITA CLASICAS INTEG 212GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CEREALITAS", "ean": "7622201736033",},
  "ARCOR HOGARENAS SALVADO CEREAL 200 GRS. PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040132962",},
  "TERRABUSI ALFAJOR 50 GRPAQ. X6 U.": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TERRABUSI", "ean": "7622300742584",},
  "TOFI ALFAJOR NEGRO 46 GRPAQ.X6 U.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TOFI", "ean": "7790040117143",},
  "SHOT BLOQUE TAB.SOLIDA 35 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SHOT", "ean": "77914217",},
  "COFLER BLOCK C/MANI TAB.SOLIDA 38 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "77953124",},
  "MILKA ALMENDRA TABLETA RELLENA 55 GR PAQ.": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622210745620",},
  "COFLER C/LECHE Y ALMENDRAS TAB.SOLIDA 55 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580033507",},
  "MILKA CHOCO PAUSE OBLEA BAN.CHO.C/LEC.RELL.45 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "MILKA CHOCO PAUSE", "ean": "7622201492717",},
  "COFLER GRAFFITI OBLEA BAN.RELLENA C/CHO. 45 GRPAQ.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GRAFFITI", "ean": "7790580111755",},
  "MILKA OREO BOMBON 19G BOLSA 1UN": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "MILKA", "ean": "77971630",},
  "BON O BON BOMBON REGULAR 15 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "BON O BON", "ean": "77958921",},
  "TANG POLVO REG NARANJA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201705961",},
  "ARCOR POLVO NARANJA REG SOBRE 15G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "ARCOR", "ean": "7790580143237",},
  "CLIGHT POLVO S/A NARANJA VIT CY D SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703110",},
  "BC LA CAMPAGNOLA SIN AZU NARANJA SOB. 7G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "BC", "ean": "7790580132774",},
  "BELDENT MENTA S/AZ. 6 TABL. PQ. 10GR": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "BELDENT", "ean": "77969071",},
  "TOP LINE S/AZUCAR SEVEN 14 GR XPLO.MINT 7 TABL.PAQ": {"empresa": "ARCOR", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "TOPLINE", "ean": "77931764",},
}
}
