productos = {
  "ARCOR POLVO LIMONADA REG SOBRE 15G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "ARCOR", "ean": "7790580143527", "cod_dia": "307054",},
  "ARCOR POLVO NARANJA MANGO REG SOBRE 15G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "ARCOR", "ean": "7790580143763", "cod_dia": "305568",},
  "ARCOR POLVO NARANJA REG SOBRE 15G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "ARCOR", "ean": "7790580143237", "cod_dia": "305566",},
  "BC LA CAMPAGNOLA NARANJA DULCE SIN AZU SOB. 7G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "BC", "ean": "7790580129965", "cod_dia": "305692",},
  "BC LA CAMPAGNOLA SIN AZU LIMONADA SOB. 7G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "BC", "ean": "7790580129941", "cod_dia": "305693",},
  "BC LA CAMPAGNOLA SIN AZU MANZANA SOB. 7G P/1L": {"empresa": "ARCOR", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "BC", "ean": "7790580129972", "cod_dia": "305694",},
  "BAGLEY AMOR DUL RELL 330GR C/3U PAQUETE AGR 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "AMOR", "ean": "7790040143500", "cod_dia": "107876",},
  "BAGLEY AMOR VAINILLA DULCE RELLENA 110GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "AMOR", "ean": "7790040143531", "cod_dia": "304730",},
  "BAGLEY SURTIDO DUL.SECA 400GR BOLSA 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BAGL SURT", "ean": "7790040147720", "cod_dia": "271962",},
  "ARCOR CEREAL MIX AVENA Y PASAS DUL.SECA PAQ. 207 G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CEREAL MIX", "ean": "7790040135741", "cod_dia": "306621",},
  "ARCOR CEREAL MIX DUL.SECA CACAO 150GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CEREAL MIX", "ean": "7790040140943", "cod_dia": "306622",},
  "ARCOR CEREAL MIX DUL.SECA FRUTILL 150GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CEREAL MIX", "ean": "7790040140936", "cod_dia": "306623",},
  "ARCOR CEREAL MIX FRUTILLA/CHIA DUL.SECA PAQ. 207 G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CEREAL MIX", "ean": "7790040135765", "cod_dia": "306624",},
  "BAGLEY CHOCOLINAS BCO DUL SEC 245GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCOLINAS", "ean": "7790040142985", "cod_dia": "241458",},
  "BAGLEY CHOCOLINAS DULCE SECA250 GRS. PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCOLINAS", "ean": "7790040143234", "cod_dia": "47932",},
  "BAGLEY CHOCOLINAS GALL DUL.SECA 181GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCOLINAS", "ean": "7790040148864", "cod_dia": "307485",},
  "BAGLEY CHOCOLINAS GALLET DUL.SEC PAQUETE 170G 1UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCOLINAS", "ean": "7790040148857", "cod_dia": "308624",},
  "BAGLEY CHOCOLINAS NEG DUL SEC. 258GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCOLINAS", "ean": "7790040142992", "cod_dia": "299715",},
  "ARCOR COFLER BLOCK DULCE SECA PAQ. 124 GR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040116955", "cod_dia": "258021",},
  "ARCOR COFLER BOB GALL RELL 85GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143807", "cod_dia": "16206",},
  "ARCOR COFLER COOKIES DULCE SECA BOLSA 120 GR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040127944", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR COFLER GALL BANADA CHC 105.6G PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143739", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR COFLER GALL OBLEAS 87GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143821", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR COFLER GALL TARTAL.BAN CHC 105.6GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143753", "cod_dia": "11817",},
  "ARCOR COFLER GALL. BAN CHC 132.8GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143692", "cod_dia": "11823",},
  "ARCOR COFLER GALLET DULCE RELL 85GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143777", "cod_dia": "3907",},
  "ARCOR COFLER GALLET DULCE RELL 85GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143784", "cod_dia": "7047",},
  "ARCOR COFLER GALLETA DULCE OBLEA 91GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COFLER", "ean": "7790040143814", "cod_dia": "NO_ENCONTRADO",},
  "BAGLEY COQUITAS DULCE SECA 260GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "COQUITAS", "ean": "7790040143265", "cod_dia": "295047",},
  "BAGLEY CRIOLLITAS TOSTADAS DULCES PAQ.195GR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CRIOLL", "ean": "7790040124530", "cod_dia": "307558",},
  "ARCOR DIVERSION SURTIDO DU.SE.REL. 400 GRBOLSA": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "DIVERSION", "ean": "7790040143364", "cod_dia": "272206",},
  "ARCOR FORMIS ANIMALES DULCES SECAS 72 GRS PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139909", "cod_dia": "116422",},
  "ARCOR FORMIS DDL DUL REL 102GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139961", "cod_dia": "118119",},
  "ARCOR FORMIS FRUTILLA DUL REL 102GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139923", "cod_dia": "118120",},
  "ARCOR FORMIS VAI/CHO DUL REL 102GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139930", "cod_dia": "107880",},
  "ARCOR FORMIS VAI/CHO DUL REL 102GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139978", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR FORMIS VAIN/FRUT DUL.RELL 72GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FORMIS", "ean": "7790040139893", "cod_dia": "115735",},
  "ARCOR MANA FRUTILLA DR 152 GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040133266", "cod_dia": "307569",},
  "ARCOR MANA LIMON DUL.RELLE.152 GR. PAQ": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040133259", "cod_dia": "272214",},
  "ARCOR MANA LIVIANAS LECHE DU.SE. PAQ 136GR 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040137813", "cod_dia": "55029",},
  "ARCOR MANA VAIN ACARAMELADA DS 145GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040151901", "cod_dia": "308671",},
  "ARCOR MANA VAIN DUL.SEC 136GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040137837", "cod_dia": "290941",},
  "ARCOR MANA VAIN DUL.SEC. 136GR PAQ 3U 408G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MANA", "ean": "7790040137844", "cod_dia": "12760",},
  "BAGLEY MELLIZAS GALL DUL RELL 330GR 1U PAQ AGR X3": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MELLIZAS", "ean": "7790040143555", "cod_dia": "307570",},
  "BAGLEY MERENGADAS DUL.REL. 88GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MERENGADA", "ean": "7790040139657", "cod_dia": "298666",},
  "BAGLEY MERENGADAS. DUL.REL. 88GR PAQ AGR 3U 264G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MERENGADA", "ean": "7790040139091", "cod_dia": "89062",},
  "ARCOR GALLETA OBLEA WF 25GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O ARCOR", "ean": "77940131", "cod_dia": "17929",},
  "BAGLEY OPERA OBLEAS 220 GRS. PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OPERA", "ean": "7790040008175", "cod_dia": "14927",},
  "BAGLEY RUMBA GALL DUL.RELL. 110GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "RUMBA", "ean": "7790040143517", "cod_dia": "55062",},
  "BAGLEY RUMBA GALLET DUL.RELL. 330GR PAQ 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "RUMBA", "ean": "7790040143524", "cod_dia": "89061",},
  "BAGLEY SONRISAS DR 108 GRS PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SONRISAS", "ean": "7790040133488", "cod_dia": "275784",},
  "BAGLEY SONRISAS FRAM DL RELLE 108GR PACK X3 U 324 G": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SONRISAS", "ean": "7790040133471", "cod_dia": "272210",},
  "BAGLEY CRIOLLITAS CRACKERS 100 GR C/U PAQ.X 3 U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CRIOLL", "ean": "7790040377806", "cod_dia": "308625",},
  "BAGLEY CRIOLLITAS ORIGINAL CR. 499G EST FAM 5X 1UN PAQ": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CRIOLL", "ean": "7790040139015", "cod_dia": "271278",},
  "BAGLEY CRIOLLITASTOST.CLAS.CRACK 195 GR PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CRIOLL", "ean": "7790040124509", "cod_dia": "186469",},
  "BAGLEY CEREAL C/SALVADO 169GR 3U PAQ AGR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "FAM", "ean": "7790040136243", "cod_dia": "268359",},
  "ARCOR HOGARENAS 7 SEMILLAS CEREAL 189GR PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040136069", "cod_dia": "307589",},
  "ARCOR HOGARENAS C/SESAMO CEREAL 167 GR PAQUE.": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040136083", "cod_dia": "307603",},
  "ARCOR HOGARENAS SALVADO CEREAL 200 G.C/U PAQ.X 3 UN": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040132955", "cod_dia": "271959",},
  "ARCOR HOGARENAS SALVADO CEREAL 200 GRS. PAQUETE": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "HOGARENAS", "ean": "7790040132962", "cod_dia": "NO_ENCONTRADO",},
  "BAGLEY KESITAS HORNEADAS SNACKS 125 GR CAJA": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "KESITAS", "ean": "7790040173200", "cod_dia": "218421",},
  "BAGLEY REX ORIGINAL SNACKS 125 GR CAJA": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "REX", "ean": "7790040719804", "cod_dia": "121118",},
  "ARCOR SALADIX JAMON SNACKS 100 GRS. CAJA ARG": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "SALADIX", "ean": "7790580716707", "cod_dia": "78685",},
  "ARCOR SALADIX PIZZA SNACKS 100 GRS. CAJA": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "SALADIX", "ean": "7790580697303", "cod_dia": "78686",},
  "BAGLEY GALL TRAVIATA ORIGINAL CR 324GR PAQ AGR 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040144088", "cod_dia": "134643",},
  "BAGLEY TRAVIATA C/REX GALL CRACKER 288GR X3 PAQ AGR 1U": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040143920", "cod_dia": "14920",},
  "BAGLEY TRAVIATA CRACKERS 108GR 5U PAQUETE 540G PAQ AGR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040144095", "cod_dia": "287902",},
  "BAGLEY TRAVIATA GALL CR C/ REX SAL ORIG 1U PAQUETE 96GR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040143937", "cod_dia": "307567",},
  "BAGLEY TRAVIATA GALL CR KESIT 1U PAQUETE 96GR": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040143944", "cod_dia": "307568",},
  "TRAVIATA BAGLEY BALANCE CR 321GR X3U PAQ": {"empresa": "ARCOR", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TRAV", "ean": "7790040142763", "cod_dia": "307560",},
  "COFLER CHOCO CREAMY ALFAJOR TRIPLE 60GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCO CREAMY", "ean": "7790040150010", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR MILK OBLE BANADA CHC 20GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "ARCOR", "ean": "7790580144227", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR TWIT O BANADOS 20GR PAQ.1U REG.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "ARCOR", "ean": "7790580132712", "cod_dia": "NO_ENCONTRADO",},
  "BON O BON BLANCA OBLEA BANADA 30 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "BON O BON", "ean": "7790580346614", "cod_dia": "23669",},
  "BON O BON OBLEA BANADA C/CHOCO. 30 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "BON O BON", "ean": "7790580346515", "cod_dia": "23675",},
  "COFLER CUBANITOS O BANADOS 29GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "COFLER", "ean": "7790580121716", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR EL KIOSCO EN CASA 246GR CAJA 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "ARCOR", "ean": "7790580131371", "cod_dia": "273222",},
  "BON O BON BOMBON BLANCO 16 GR.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "BON O BON", "ean": "77961815", "cod_dia": "NO_ENCONTRADO",},
  "BON O BON BOMBON REGULAR 15 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "BON O BON", "ean": "77958921", "cod_dia": "17930",},
  "HAMLET BOMBON LECHE C/CEREAL CROCANTE 13 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "HAMLET", "ean": "77959041", "cod_dia": "NO_ENCONTRADO",},
  "ROSPO SAPITO BOCADITO RE.CHOCOL. 10.5 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "ROSPO", "ean": "77928894", "cod_dia": "NO_ENCONTRADO",},
  "ROSPO SAPITO BOCADITO RELL.FRUT. 10 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "ROSPO", "ean": "77917393", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR MANI BANADO MANI CH 35GR BOLSA 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "CONFITURAS", "marca": "ARCOR", "ean": "7790580128043", "cod_dia": "NO_ENCONTRADO",},
  "BON O BON CITOS CONFITADOSPOTE 200 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "CONFITURAS", "marca": "BON O BON", "ean": "7790580111243", "cod_dia": "NO_ENCONTRADO",},
  "ROCKLETS GRAGEAS C/CHOCOLATE 20 GRBOLSA": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "CONFITURAS", "marca": "ROCKLETS", "ean": "7790580421007", "cod_dia": "NO_ENCONTRADO",},
  "ROCKLETS NAVIDAD GRAGEAS C/CHOCO. 120 GRBOLSA": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "CONFITURAS", "marca": "ROCKLETS", "ean": "7790580415808", "cod_dia": "77437",},
  "BON O BON HUEVO DE CHOCOLATE C/LECHE 110 GRPAS/NAV.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "BON O BON", "ean": "7790580587802", "cod_dia": "NO_ENCONTRADO",},
  "BON O BON HUEVO DE CHOCOLATE C/LECHE 55 GRPAS/NAV.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "BON O BON", "ean": "7790580587901", "cod_dia": "NO_ENCONTRADO",},
  "SAPITO CON CONFITES 28GR HYF 1U BOLSA": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "SAPITO", "ean": "7790580131524", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR C/LECHE TAB.SOLIDA 25 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "ARCOR", "ean": "7790580607210", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR MILK RELLE. 12GR PAQUETE 1U 35% LECHE": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "ARCOR", "ean": "77977991", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR SOLIDAS C/LECHE Y MANI 95GR 1U PAQ": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "ARCOR", "ean": "7790580123734", "cod_dia": "NO_ENCONTRADO",},
  "COFLER AIR CHO.C/LEC.TAB.AIREA. 55 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580033408", "cod_dia": "NO_ENCONTRADO",},
  "COFLER BLOCK TAB.SOLIDA 110 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "77922120", "cod_dia": "NO_ENCONTRADO",},
  "COFLER BON O BON RELLENO BON O BON 67 GRTAB.AIREA.": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580115562", "cod_dia": "NO_ENCONTRADO",},
  "COFLER C/CHOCOLINAS SOLIDAS 55GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580103538", "cod_dia": "NO_ENCONTRADO",},
  "COFLER C/LECHE Y ALMENDRAS TAB.SOLIDA 55 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580033507", "cod_dia": "NO_ENCONTRADO",},
  "COFLER ROCKLETS TAB.SOLIDA 55 GR": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580103521", "cod_dia": "NO_ENCONTRADO",},
  "COFLER TABLETA CHC 60%CACAO SOLIDA 100GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580141776", "cod_dia": "NO_ENCONTRADO",},
  "COFLER TABLETA CHC 60%CACAO SOLIDA 100GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580143862", "cod_dia": "NO_ENCONTRADO",},
  "COFLER TABLETA CHC SOLIDA 100GR PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580141752", "cod_dia": "NO_ENCONTRADO",},
  "COFLER YOGURT FRUTILLA RELL 64GR PAQUETE 1UN": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "COFLER", "ean": "7790580123642", "cod_dia": "NO_ENCONTRADO",},
  "HAMLET LECHE MANI ALMENDRA CEREAL 45 GRTAB.SOLIDA": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HAMLET", "ean": "7794612065719", "cod_dia": "NO_ENCONTRADO",},
  "COFLER ROCKLETS SOLIDAS 18 PAQUETE 1U": {"empresa": "ARCOR", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "ROCKLETS", "ean": "77987112", "cod_dia": "NO_ENCONTRADO",},
  "TOP LINE S/AZUCAR 6.7 GR FRUTA 4 TABL.PAQ.": {"empresa": "ARCOR", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "TOPLINE", "ean": "77916389", "cod_dia": "NO_ENCONTRADO",},
  "TOP LINE S/AZUCAR 6.7 GR MENTA 4 TABL.PAQ.": {"empresa": "ARCOR", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "TOPLINE", "ean": "77916426", "cod_dia": "NO_ENCONTRADO",},
  "CLIGHT ED LIM POMELADA HIBISCUS SIN AZUCARES SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622202359934", "cod_dia": "309744",},
  "CLIGHT LIMONADA ARANDANOS DIET SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622202236846", "cod_dia": "305575",},
  "CLIGHT LIMONADA ROSA S/AZUCARES SOBRE 7.5G P/1 L.": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201682026", "cod_dia": "139870",},
  "CLIGHT NAR/DUR S/A VITC+D SOBRE 7.5G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201702717", "cod_dia": "274274",},
  "CLIGHT POLVO ANANA SOBRE 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201702625", "cod_dia": "274279",},
  "CLIGHT POLVO DIET MANZANA DELI. SOBRE 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703080", "cod_dia": "274216",},
  "CLIGHT POLVO NARA MANGO DIET SOBRE 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201702687", "cod_dia": "274275",},
  "CLIGHT POLVO S/A LIMONADA VITC+D SOBRE 8GR P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201702656", "cod_dia": "274273",},
  "CLIGHT POLVO S/A MANDARINA SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201704148", "cod_dia": "274276",},
  "CLIGHT POLVO S/A NARANJA VIT CY D SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703110", "cod_dia": "274217",},
  "CLIGHT PVO S/A MANZANA VERDE SOBRE 7.5GR P/1LT": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703059", "cod_dia": "274277",},
  "CLIGHT PVO S/A NARANJA DULCE VIT C Y D SOBRE 7.5G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703141", "cod_dia": "274215",},
  "CLIGHT PVO S/A POMELO ROSADO VIT C Y D SOBRE 8G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "CLIGHT", "ean": "7622201703172", "cod_dia": "282436",},
  "TANG GALACTICO ED. LIM POLVO FRUTAL REG SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622202311482", "cod_dia": "309745",},
  "TANG POLV POM ROSADO REG SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735746", "cod_dia": "274211",},
  "TANG POLVO REG ANANA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201745967", "cod_dia": "274213",},
  "TANG POLVO REG LIMONADA DULCE SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735685", "cod_dia": "274212",},
  "TANG POLVO REG MANDARINA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201733865", "cod_dia": "305576",},
  "TANG POLVO REG MANZANA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201705992", "cod_dia": "274181",},
  "TANG POLVO REG MULTIFRUTA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735715", "cod_dia": "274183",},
  "TANG POLVO REG NARA/BANANA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735777", "cod_dia": "274184",},
  "TANG POLVO REG NARA/MANGO SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735371", "cod_dia": "274182",},
  "TANG POLVO REG NARANJA DULCE SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201735340", "cod_dia": "274180",},
  "TANG POLVO REG NARANJA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201705961", "cod_dia": "274179",},
  "TANG POLVO REG UVA SOBRE 15G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "TANG", "ean": "7622201746117", "cod_dia": "274214",},
  "VERAO POLVO MANZANA REG SOB. 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "VERAO", "ean": "7622201717445", "cod_dia": "203850",},
  "VERAO POLVO NAR/DURAZNO REG SOB. 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "VERAO", "ean": "7622201717476", "cod_dia": "203849",},
  "VERAO POLVO NARANJA REG SOB. 7G P/1L": {"empresa": "MONDELEZ", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "VERAO", "ean": "7622201717414", "cod_dia": "203847",},
  "MONDELEZ CEREALITAS GRANOLA D.S. 170GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CEREALITAS", "ean": "7622202241567", "cod_dia": "6273",},
  "MDLZ TERRABUSI.DUQUESA GALL DUL. REL 115GR PAQ 3U 345GR": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "DUQUESA", "ean": "7622202218729", "cod_dia": "3909",},
  "MONDELEZ TERRABUSI DUQUESA DUL.RELLE. 115 GRPAQUETE": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "DUQUESA", "ean": "7622300742645", "cod_dia": "73265",},
  "MONDELEZ TERRABUSI MELBA DUL.RELLE. 120 GRPAQUETE": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MELBA", "ean": "7622300829728", "cod_dia": "73264",},
  "TERRABUSI MELBA ANGRY BIRDS DU.REL.PAQ.120GR C/UPACK X 3 U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MELBA", "ean": "7794600004539", "cod_dia": "52289",},
  "MONDELEZ INTL.MILKA GALL. REL C/MOUS 124GR PAQUETE 1UN": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MILKA", "ean": "7622202210075", "cod_dia": "25357",},
  "MONDELEZ OREO D.R. 118GR 3U 354G PQ AGR": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201735258", "cod_dia": "271630",},
  "MONDELEZ OREO D.R. 118GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201735296", "cod_dia": "271629",},
  "MONDELEZ OREO DUL.REL. 182.5GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201735821", "cod_dia": "271631",},
  "MONDELEZ OREO MINI DUL.RELLE 50GR BOLSA 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201761288", "cod_dia": "175320",},
  "MONDELEZ OREO SIN GLUTEN GALL DR 95GR PAQUETE 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622202038099", "cod_dia": "4522",},
  "MONDELEZ OREO VAINILLA GOLDEN 118GR PAQ.DU.RE 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "OREO", "ean": "7622201806552", "cod_dia": "283177",},
  "MONDELEZ PEPITOS C/CHISPAS DS 119 GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PEPITOS", "ean": "7622201735906", "cod_dia": "271628",},
  "MONDELEZ PEPITOS MINI. DULCE SECA 50GR BOLSA 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PEPITOS", "ean": "7622201740399", "cod_dia": "176893",},
  "MONDELEZ PEPITOS. DU. SEC 119GR 3UN 357G PAQ AGR": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PEPITOS", "ean": "7622201735883", "cod_dia": "271632",},
  "MONDELEZ LINCOLN ANGRY.BIRD DUL SEC 153GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201745523", "cod_dia": "169935",},
  "MONDELEZ TERRABUSI VARIED.MIX DU.SE. 590GR BOL": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201745585", "cod_dia": "284655",},
  "MONDELEZ.TERRABUSI VARIED.MIX DU.SE. 390GR BOL": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201745561", "cod_dia": "284571",},
  "TERRABUSI LINCOLN CLASICA. D.S. 3U 153GR PQ AGR 459G": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201745547", "cod_dia": "170177",},
  "TERRABUSI VARIEDAD CHC DUL.SEC 300GR BOLSA 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TERRABUSI", "ean": "7622201503987", "cod_dia": "274330",},
  "MONDELEZ CEREALITA CLASICA INT 212GR PAQ 3U 636G": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CEREALITAS", "ean": "7622201745905", "cod_dia": "147685",},
  "MONDELEZ CEREALITA CLASICAS INTEG 212GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CEREALITAS", "ean": "7622201736033", "cod_dia": "147689",},
  "MONDELEZ CLUB.SOCIAL ORIGINAL 144 GR PAQ 1U": {"empresa": "MONDELEZ", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "CLUB SOCIAL", "ean": "7622202293740", "cod_dia": "226391",},
  "MILKA ALFAJOR TRIPLE 70 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "MILKA", "ean": "77903778", "cod_dia": "23428",},
  "MILKA MOUSSE LECHE ALFAJOR 42 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "MILKA", "ean": "7622300759506", "cod_dia": "110564",},
  "MILKA MOUSSE TRIPLE ALFAJOR 55 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "MILKA", "ean": "77903785", "cod_dia": "21721",},
  "MILKA MOUSSE TRIPLE BLANCO ALF. 55 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "MILKA", "ean": "7622300457303", "cod_dia": "276726",},
  "MILKA TORTA OREO ALF.TRIPLE 61 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "MILKA", "ean": "7622300835620", "cod_dia": "182539",},
  "OREO ALFAJOR TRIPLE. 56GR 1U PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "OREO", "ean": "77976307", "cod_dia": "274632",},
  "PEPITOS CON CHIPS Y MOUSSE TRIPLE PAQUETE 57 GR UN.": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "PEPITOS", "ean": "77915481", "cod_dia": "23430",},
  "SHOT ALFAJOR MANI BAN CHC SIMPLE 44GR PAQUETE 1UN": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "SHOT", "ean": "7622202304705", "cod_dia": "308300",},
  "SHOT ALFAJOR TRIPLE 60 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "SHOT", "ean": "77956699", "cod_dia": "23431",},
  "TERRABUSI ALFAJOR CHOCOLATE 50 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TERRABUSI", "ean": "77939234", "cod_dia": "149060",},
  "TERRABUSI X 3 DCE.DE LE.ALFAJOR 70 GRTRIPLE": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TERRABUSI", "ean": "77903792", "cod_dia": "23423",},
  "TERRABUSI X 3 TORTA ALFAJOR 70 GRTRIPLE": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TERRABUSI", "ean": "77903860", "cod_dia": "23426",},
  "TITA NEGRO ALFAJOR RELL.LIMON 36 GRARG": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TITA", "ean": "77908308", "cod_dia": "303490",},
  "MILKA CHOCO PAUSE.OREO OBLEA BAN.CHC 45GR 1U PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "MILKA", "ean": "7622201492465", "cod_dia": "260584",},
  "MILKA CHOCO PAUSE OBLEA BAN.CHO.C/LEC.RELL.45 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "MILKA CHOCO PAUSE", "ean": "7622201492717", "cod_dia": "278032",},
  "RHODESIA OBLEA BAN.C/CHO. 22 GRBOLSA": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "RHODESIA", "ean": "77995681", "cod_dia": "17932",},
  "TITA O BANADOS 19GR PAQ 1U REGULAR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "TITA", "ean": "77976291", "cod_dia": "274902",},
  "MILKA OREO BOMBON 19G BOLSA 1UN": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "MILKA", "ean": "77971630", "cod_dia": "272322",},
  "MILKA HUEVO CHOC 157GR 1U S/SORP PAS/NAV": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "MILKA", "ean": "7622202267796", "cod_dia": "246321",},
  "MILKA HUEVO LECHE 22GR 1U S/SORP PAS": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "MILKA", "ean": "77981325", "cod_dia": "6205",},
  "CADBURY C/YOGHURT. NUEZ TAB. RELL.29GR 1U PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "CADBURY", "ean": "7622201818654", "cod_dia": "21637",},
  "CADBURY YOGHURT FRUTILLA RELL 82 GRS PAQUETE 1U": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "CADBURY", "ean": "7622201818715", "cod_dia": "274637",},
  "MILKA . TAB CHC SOLIDA 20GRS PAQUETE 1U": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622210795625", "cod_dia": "252365",},
  "MILKA ALMENDRA TABLETA RELLENA 55 GR PAQ.": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622210745620", "cod_dia": "249905",},
  "MILKA C/LECHE TAB.SOLIDA 150 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622300990114", "cod_dia": "222262",},
  "MILKA CHOCO.C/LECHE TAB.SOLIDA 55 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622210745224", "cod_dia": "249906",},
  "MILKA LEGER COMBINADO TAB AIREA. LECHE 110GR 1U": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622201812775", "cod_dia": "274865",},
  "MILKA OREO TAB. SOLIDA 20GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622210795908", "cod_dia": "252368",},
  "MILKA TAB CHC AIREADA C.LECHE 25GR 1UN PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622202322150", "cod_dia": "182540",},
  "MILKA TAB CHC AIREADA COMBINADO 25GR 1UN PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622202322181", "cod_dia": "110569",},
  "MILKA TABLETA CHC RELLENA 29GR PAQUETE 1UN": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622202322068", "cod_dia": "134986",},
  "MILKA TABLETA CHC RELLENA 29GR PAQUETE 1UN": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MILKA", "ean": "7622202322129", "cod_dia": "135191",},
  "SHOT BLOQUE TAB.SOLIDA 35 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SHOT", "ean": "77914217", "cod_dia": "110388",},
  "SHOT C/LECHE Y MANI TAB.SOLIDA 170 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SHOT", "ean": "7622300424084", "cod_dia": "121964",},
  "SHOT C/MANI TAB.SOLIDA 90 GR": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SHOT", "ean": "7791249451656", "cod_dia": "168862",},
  "SHOT CHOCOLAE C/MANI TAB.SOLIDA 35 GR 1U PAQ": {"empresa": "MONDELEZ", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SHOT", "ean": "77983992", "cod_dia": "296637",},
  "BELDENT CHI. TABLETA ADU. S/AZ. 6 CHI. PQ. 10GR 1UN": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "BELDENT", "ean": "77969101", "cod_dia": "270871",},
  "BELDENT FRUTILLA S/AZ. 6 TABL. PQ. 10GR": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "BELDENT", "ean": "77969118", "cod_dia": "271838",},
  "BELDENT MENTA FUERTE S/AZ. 6 TABL. PQ. 10GR": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "BELDENT", "ean": "77969088", "cod_dia": "269579",},
  "BELDENT MENTA S/AZ. 6 TABL. PQ. 10GR": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "ADULTOS", "marca": "BELDENT", "ean": "77969071", "cod_dia": "269580",},
  #N/A
  "BUBBALOO MENTA CHIC. GLOBO INF. ENVOL. 5GR 1UN": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "INFANTILES", "marca": "BUBBALOO", "ean": "77982346", "cod_dia": "288528",},
  "BUBBALOO TUTTI-FRUTTI CHIC. GLOBO INF. ENVOL. 5GR 1UN": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "INFANTILES", "marca": "BUBBALOO", "ean": "77982353", "cod_dia": "288529",},
  "BUBBALOO UVA CHIC. GLOBO INF. ENVOL. 5GR 1UN": {"empresa": "MONDELEZ", "categoría": "Gums", "subcategoría": "INFANTILES", "marca": "BUBBALOO", "ean": "77982377", "cod_dia": "288531",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "FRUTA FRESH POLVO MANZANA DIET SOBRE 8G P/1L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "O MARCAS", "ean": "7798153250993", "cod_dia": "297927",},
  "FRUTA FRESH POLVO MIX FRUTAL DIET SOBRE 8G P/1L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "O MARCAS", "ean": "7798153250979", "cod_dia": "118528",},
  "FRUTA FRESH POLVO NARANJA DIET SOBRE 8G P/1L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "O MARCAS", "ean": "7798153250986", "cod_dia": "118532",},
  "RINDE DOS 1+1 POLVO MANZANA DIET SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908404763", "cod_dia": "15023",},
  "RINDE DOS ANANA BAJAS CAL SOBRE 13G P/2LT": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908401588", "cod_dia": "151228",},
  "RINDE DOS LIMON DIET SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908401540", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS MIX FRUTAL POLVO BAJAS CAL. SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908400536", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS NARA/MANGO POLVO S/AZU. SOBRE 15GR P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908402554", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS PERA POLVO BAJAS CAL. SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908401847", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS POLVO 1+1 NARANJA DIET SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908404756", "cod_dia": "3975",},
  "RINDE DOS POLVO DIET NARANJA SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908400529", "cod_dia": "131967",},
  "RINDE DOS POLVO DIET TERERE LIMONADA SOBRE 6.5 P/2LT": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908405128", "cod_dia": "309555",},
  "RINDE DOS POLVO DURAZNO BAJAS CAL. SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908400543", "cod_dia": "162147",},
  "RINDE DOS POLVO LIMON 1+1 DIET SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908404770", "cod_dia": "3134",},
  "RINDE DOS POLVO MANZANA DIET SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908400567", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS POLVO NAR/BANA BAJAS CAL. SOBRE 13G P/2L": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908400987", "cod_dia": "137433",},
  "RINDE DOS POLVO POMELO ROSADO DIET SOBRE 13G P/2LT": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908402578", "cod_dia": "NO_ENCONTRADO",},
  "RINDE DOS PVO 1L+1L TERERE NARA CITRU DIET SOB 13G P/2LT 1U": {"empresa": "RESTO", "categoría": "Beverages", "subcategoría": "Pbs", "marca": "RINDE DOS", "ean": "7730908405104", "cod_dia": "309554",},
  "M CANUELAS 9 DE ORO COOKIE C/CHIP 120GR PAQ.DU.SE.": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "9 DE ORO", "ean": "7792180138491", "cod_dia": "NO_ENCONTRADO",},
  "M.CANUELAS 9 DE ORO SCONS LIMON DULCE SECA 180 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "9 DE ORO", "ean": "7792180009524", "cod_dia": "273728",},
  "M.CANUELAS9 DE ORO BIZ CARA SUCIA DULC SECA 200GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "9 DE ORO", "ean": "7792180143587", "cod_dia": "40390",},
  "M.CANUELAS9 DE ORO BIZC.AZUC.DULCE SECA 210 GRSPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "9 DE ORO", "ean": "7792200000319", "cod_dia": "4055",},
  "M.CANUELAS9 DE ORO CUAD.AGRI.DULCE SECA 200 GRBOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "9 DE ORO", "ean": "7792200000128", "cod_dia": "58649",},
  "BAUDUCCO FRESA OBLEA 140 GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BAUDUCCO", "ean": "7891962032283", "cod_dia": "122578",},
  "BAUDUCCO VAINILLA OBLEA 140 GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BAUDUCCO", "ean": "7891962032306", "cod_dia": "3182",},
  "BAUDUCCO WAFER CHOCOLATE OBLEA 140 GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BAUDUCCO", "ean": "7891962032290", "cod_dia": "124510",},
  "BONAFIDE DONUTS BAN.C/CHO 78GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BONAFIDE", "ean": "7792360096818", "cod_dia": "107601",},
  "BONAFIDE DONUTS BAN.C/CHO 78GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "BONAFIDE", "ean": "7792360096825", "cod_dia": "24917",},
  "CHOCMAN BIZCOCHUELO BAN CHC 68GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCMAN", "ean": "7792360096658", "cod_dia": "NO_ENCONTRADO",},
  "CHOCMAN BIZCOCHUELO COCO BAN CHC 35GR 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCMAN", "ean": "7792360097075", "cod_dia": "NO_ENCONTRADO",},
  "CHOCMAN BLACK BIZCOCHUELO BAN CHC 35GR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCMAN", "ean": "7792360096597", "cod_dia": "NO_ENCONTRADO",},
  "CHOCMAN MINITORTA BLACK BAN CHC 68GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCMAN", "ean": "7792360096580", "cod_dia": "NO_ENCONTRADO",},
  "CHOCMAN MINITORTA RELLENA C/D.D.LECHE 35 GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "CHOCMAN", "ean": "7792360096634", "cod_dia": "NO_ENCONTRADO",},
  "PEPSICO DALE VAINILLA DUL.RELLE. 81 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "DALE", "ean": "7798113151278", "cod_dia": "NO_ENCONTRADO",},
  "CACHAFAZ INTEGRAL AVE.PASA DE UVA D.S. 225 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "EL CACHAFAZ", "ean": "7798128000677", "cod_dia": "19294",},
  "CACHAFAZ INTEGRAL AVEN.C/CHIP.CHOC.D.S. 225 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "EL CACHAFAZ", "ean": "7798128000691", "cod_dia": "57302",},
  "CACHAFAZ INTEGRAL GRAN.C/AVENA/ALM/MANI 225 GRPAQ.DU.SE.": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "EL CACHAFAZ", "ean": "7798128000707", "cod_dia": "14916",},
  "CACHAFAZ INTEGRAL HAR.INT.ALGARRO.D.S. 225 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "EL CACHAFAZ", "ean": "7798128000684", "cod_dia": "54455",},
  "GRANIX FRUTIGRAN AVE/SOJA C/CHIPS CHOC.D.SECA 255 PAQ.": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FRUTIGRAN", "ean": "7790045824893", "cod_dia": "NO_ENCONTRADO",},
  "GRANIX FRUTIGRAN SALV.AVENAPAS.DE UVA 250 GRS.DU.SE.PAQ.": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FRUTIGRAN", "ean": "7790045001188", "cod_dia": "NO_ENCONTRADO",},
  "GRANIX FRUTIGRAN SALVADO DULCE SECA 250 GRS.PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "FRUTIGRAN", "ean": "7790045001195", "cod_dia": "NO_ENCONTRADO",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "LIA MACUCAS BLACK GALL DUL RELL 110GR PAQ SPL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MACUCAS", "ean": "7790040150461", "cod_dia": "NO_ENCONTRADO",},
  "LIA MACUCAS CHOCOLATE DUL.RELLE.85 GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MACUCAS", "ean": "7790040146877", "cod_dia": "NO_ENCONTRADO",},
  "LIA MACUCAS GALL DUL RELL 110GR PAQ SPL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "MACUCAS", "ean": "7790040145337", "cod_dia": "272217",},
  "DON SATUR BIZCOCHO DULCE DULCE SECA 200 GRBOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O DSATUR", "ean": "7795735000335", "cod_dia": "216576",},
  "DON SATUR NEGRITOS DULCE SECA 200 GRBOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O DSATUR", "ean": "7795735000342", "cod_dia": "216577",},
  "ALFA PAMPA GALL.RELL.LIMON C/BANO 19GR 1UN PAQ": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798171732914", "cod_dia": "NO_ENCONTRADO",},
  "ARBANIT GALLETA OB/WF 26GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "736372567604", "cod_dia": "NO_ENCONTRADO",},
  "ARBANIT GALLETA OB/WF 26GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "754697494443", "cod_dia": "305820",},
  "ARBANIT OBLEA RELLENA AVELLANA PAQUETE 28 GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "754697494481", "cod_dia": "253563",},
  "ARBANIT OBLEA RELLENA DULCE DE LECHE 28GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "754697494498", "cod_dia": "8257",},
  "ARBANIT OBLEA RELLENA MARACUYA 28GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "763331452206", "cod_dia": "NO_ENCONTRADO",},
  "ARBANIT OBLEA RELLENA MARROC 28GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "763331452169", "cod_dia": "NO_ENCONTRADO",},
  "CELOSA GALLETITASVAINILLA BAN.C/CHO. 110 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798036830168", "cod_dia": "298489",},
  "CELOSA GALLETITASVAINILLA BAN.C/CHO. 230 GRBOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798036830175", "cod_dia": "185376",},
  "DEUBEL PALMERITA DE MANTEC.DUL.SECA 200 GRS. BANDEJA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7791696008014", "cod_dia": "307470",},
  "EDRA SURTIDAS DUL.SECA 300 GRS. BOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798048730395", "cod_dia": "124072",},
  "FIRENZE PAMELA C/CHIPS CHO.DU.SE. 180 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7791568000702", "cod_dia": "NO_ENCONTRADO",},
  "FIRENZE PAMELA VAINILLA DUL.RELLE. 97 GRPACK X 3 U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7791568001037", "cod_dia": "NO_ENCONTRADO",},
  "FIRENZE PAMELAS GALLETA CHO DUL. SEC. 170GR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7791568006100", "cod_dia": "NO_ENCONTRADO",},
  "FULBITO OBLEA RELL. MOUSSE CHOC 25G 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798094223650", "cod_dia": "299081",},
  "GAONA CHIPS CHOCOLATE DULCE SECA 230 GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798126072782", "cod_dia": "289216",},
  "GAONA SINFONIA OBLEA OB/WF BLACK 100GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798126074144", "cod_dia": "308588",},
  "GAONA SINFONIA OBLEAS CALSSSIC 50GR X4IU PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798126072805", "cod_dia": "289217",},
  "GAONA STAR CHIPS DUL.SECA 230 GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798126071150", "cod_dia": "289219",},
  "JUNCALCOR KUKINAS GALL DUL. SECA C/CHISP 50GR PAQ 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810232", "cod_dia": "309068",},
  "KUKINAS DUL SEC CHIPS CHOC 80GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810133", "cod_dia": "305294",},
  "KUKINAS DULCE SECA CHOCOLATE 80 PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810010", "cod_dia": "77364",},
  "KUKINAS DULCE SECA VAINILLA 180GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810034", "cod_dia": "305318",},
  "KUKINAS DULCE SECA VAINILLA 180GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810072", "cod_dia": "305317",},
  "KUKINAS GALLETAS DULCE RELL 65GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810218", "cod_dia": "38572",},
  "KUKINAS GALLETAS DULCE RELL 65GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810225", "cod_dia": "NO_ENCONTRADO",},
  "KUKINAS GALLETAS DULCE RELL 65GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810317", "cod_dia": "NO_ENCONTRADO",},
  "KUKINAS GALLETAS DULCE.SECA C/CHISP 175GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798360810195", "cod_dia": "14917",},
  "LEIVA DULCE DE LECHE DUL.SECA 260 GR PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790412000011", "cod_dia": "NO_ENCONTRADO",},
  "MONTE NIEVAS CELOSAS POLV.VAINIL. DUL.SECA 250GR. BOL": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798036830250", "cod_dia": "301307",},
  "MONTE NIEVAS POLVORONESDUL.SECA 380 GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798036830229", "cod_dia": "NO_ENCONTRADO",},
  "NEVARES TURRON MANI 25GR 1U PAQ": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "77923523", "cod_dia": "NO_ENCONTRADO",},
  "PAR-NOR GALL CHIPPIS CHOC DUL.SEC. 120GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7791324157664", "cod_dia": "285932",},
  "POZO GALL VAINILLAS DUL. SEC. 80GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790077000326", "cod_dia": "NO_ENCONTRADO",},
  "POZO GALL VAINILLAS DULCE SECA 148GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790077001354", "cod_dia": "NO_ENCONTRADO",},
  "SMACK . TORTA BANADA RELL DDL 70GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7798094223063", "cod_dia": "NO_ENCONTRADO",},
  "ZUPAY BLOKE OBLE.FRUTILLA DUL.RELLE. 100 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790349000825", "cod_dia": "NO_ENCONTRADO",},
  "ZUPAY BLOKE OBLEAS VAINILLA 100 GRBOL.DU.RE.": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790349000818", "cod_dia": "308804",},
  "ZUPAY OBLEA BLOKE NUTELA 100 GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790349000870", "cod_dia": "NO_ENCONTRADO",},
  "ZUPAY OBLEAS LIMON DUL.RELLE. 50 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O MARCAS", "ean": "7790349000054", "cod_dia": "NO_ENCONTRADO",},
  "SORIANO BISCUIT DULCE SECA 125 GRS.PAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "O SORIANO", "ean": "7792184003085", "cod_dia": "259547",},
  "PAR-NOR MINI PITU.CHOC.RELL.C/CRE.SAB.LECHE 160GBOLSA.ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PITUSAS", "ean": "7791324157046", "cod_dia": "231936",},
  "PAR-NOR MINI PITUSAS BLACK DUL.REL 130GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PITUSAS", "ean": "7791324157633", "cod_dia": "138144",},
  "PAR-NOR MINI PITUSAS FRUTIL.DUL.RELLE.160 GRS. BOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "PITUSAS", "ean": "7791324157466", "cod_dia": "231934",},
  "LIA POLVORITA CHOC DUL.RELLE.81GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "POLVORITA", "ean": "7790040139183", "cod_dia": "NO_ENCONTRADO",},
  "LIA POLVORITA FRUT DUL.RELLE.81GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "POLVORITA", "ean": "7790040139176", "cod_dia": "NO_ENCONTRADO",},
  "LIA POLVORITA VAIN DUL.RELLE.81GR PAQ 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "POLVORITA", "ean": "7790040139169", "cod_dia": "NO_ENCONTRADO",},
  "RIERA TOSTADAS DULCES DULCE SECA 200GR BOL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "RIERA", "ean": "7790071090125", "cod_dia": "299813",},
  "SMAMS GALLETITAS C/CHIPS DUL SEC 120GR BOL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SMAMS", "ean": "7798181511349", "cod_dia": "295831",},
  "SOLITAS EKIN CHOC DUL. RELL. BOLSA 160GR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684003745", "cod_dia": "260952",},
  "SOLITAS EKIN VAIN DUL. RELL. BOLSA 160GR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684003868", "cod_dia": "NO_ENCONTRADO",},
  "SOLITAS PENSAMIEN-TOS DUL.SECAS 350 GR BOLSA ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684001253", "cod_dia": "307363",},
  "SOLITAS PRINCES GALL CHOC DR BOLSA 160GR 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684003998", "cod_dia": "307364",},
  "SOLITAS PRINCESS GALLET DUL RELL 80GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684004209", "cod_dia": "NO_ENCONTRADO",},
  "SOLITAS SURTISOL SURTIDAS DULCE SECABOL.180 GR2684000294": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "SOLITAS", "ean": "7792684000294", "cod_dia": "NO_ENCONTRADO",},
  "TEPERIN PEPAS DUL. SECA PAQUETE 200 GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "TEREPIN", "ean": "7798054220156", "cod_dia": "299852",},
  "LIA VOCACION GALL DULCE SEC 384GR 3U PAQ AGR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "DULCES", "marca": "VOCACION", "ean": "7790040143623", "cod_dia": "308717",},
  "M.CANUELAS9 DE ORO BIZC.CLAS.CRACKERS 200 GR PAQUE.ARG": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "9 DE ORO", "ean": "7792200000159", "cod_dia": "58648",},
  "DON SATUR 100% VEGETAL . BIZCOCHOS 170 GRS BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "D SATUR BIZ", "ean": "7795735601228", "cod_dia": "300113",},
  "DON SATUR BIZCOCHOS SALADOS CRACKERS PAQ.200 GR5735000328": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "D SATUR BIZ", "ean": "7795735000328", "cod_dia": "216575",},
  "GRANIX GRAN AGUA SANDWICH CRACKERS PAQ.200 X30045001379": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "GRANAGUA", "ean": "7790045001379", "cod_dia": "NO_ENCONTRADO",},
  "GRANIX GALLETAS CR 600GR 1UN PAQUETE AGR X3": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "GRANIX", "ean": "7790045827740", "cod_dia": "NO_ENCONTRADO",},
  "LA PROVIDENCIA CRACKERS PAQ. FAM. X 5 U. 101 GR C/U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "LA PROVIDENCIA", "ean": "7798141972388", "cod_dia": "299850",},
  "M CANUELAS 9 DE ORO GALL SN ORIG 120GR BOLSA 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "M CA¥UELAS 9 ORO", "ean": "7792180146090", "cod_dia": "309754",},
  "M CANUELAS 9 DE ORO GALL SN QUESO 120GR BOLSA 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "M CA¥UELAS 9 ORO", "ean": "7792180146106", "cod_dia": "309753",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "ARCOR MEDIA TARDE SANDWICH CRACKERS 107 GR PAQ.X 5U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "MEDIA TARDE", "ean": "7790040143012", "cod_dia": "307559",},
  "LIA MEDIA TARDE GALL CR 315GR PAQUE AGR 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "MEDIA TARDE", "ean": "7790040143586", "cod_dia": "285041",},
  "DON SATUR TALITAS CRACKERS 140 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O DSATUR", "ean": "7795735000106", "cod_dia": "237234",},
  "M CANUELAS PASEO GALLETAS SN QUESO 250GR BOLSA 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7792180145444", "cod_dia": "40337",},
  "MOLINOS ALA TOST.ARROZ CLAS.CRACKERS 150 GRPAQUETE": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7791120098093", "cod_dia": "NO_ENCONTRADO",},
  "NEOSOL GALLETAS SNACKS JAMON 70GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7796624012101", "cod_dia": "NO_ENCONTRADO",},
  "NEOSOL GALLETAS SNACKS PIZZA 70GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7796624012118", "cod_dia": "NO_ENCONTRADO",},
  "PAMELA GALL MATERA CR 180GR BOLSA 1UN": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7791568006445", "cod_dia": "308591",},
  "PANEX BIZCOCHITODE GRASA CRACKERS 200 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7798016323284", "cod_dia": "NO_ENCONTRADO",},
  "PIPAS GALLET CRACKERS C/SEM GIR 100GR BOLSA 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7798044151354", "cod_dia": "NO_ENCONTRADO",},
  "TOSTI TOSTADAS CLASICAS PAQ 200GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "O MARCAS", "ean": "7794529041608", "cod_dia": "295252",},
  "M.CANUELASPASEO MINI CRACKERS 300 GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "PASEO", "ean": "7792180006448", "cod_dia": "263978",},
  "M.CANUELASPASEO MINI SALVADO CEREAL 300 GRBOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "PASEO", "ean": "7792180006455", "cod_dia": "257613",},
  "M.CANUELASPASEO MINICRACKERS 5 SEMILLAS 300 GRBOL.CEREAL": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "PASEO", "ean": "7792180007315", "cod_dia": "257614",},
  "RIERA TOSTADAS CLASICA CRACKERS 200 GR PAQUE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "RIERA", "ean": "7790071090231", "cod_dia": "299814",},
  "RIERA TOSTADAS INTEGRAL 200GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "RIERA", "ean": "7790071070318", "cod_dia": "307624",},
  "RIERA TOSTADAS INTEGRAL 200GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "RIERA", "ean": "7790071090330", "cod_dia": "299717",},
  "RIERA TOSTADAS LIGHT PAQUETE 200G PAQUETE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "RIERA", "ean": "7790071070134", "cod_dia": "299716",},
  "RIERA TOSTADAS S/SAL CRACK 200 GR PAQUE 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "RIERA", "ean": "7790071090422", "cod_dia": "307623",},
  "SMAMS CRACKERS CRACKERS BOLSA 150 GR": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "SMAMS", "ean": "7798181510212", "cod_dia": "266047",},
  "SOLITAS BIZCOCHO CON GRASA 180GR BOL 1U": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "SOLITAS", "ean": "7792684003707", "cod_dia": "NO_ENCONTRADO",},
  "TWISTOS MINI TOST.JAMON 95GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TWISTOS", "ean": "7790310983256", "cod_dia": "147642",},
  "TWISTOS MINI TOST.QUESO 95GR BOLSA": {"empresa": "RESTO", "categoría": "Biscuits", "subcategoría": "SALADAS", "marca": "TWISTOS", "ean": "7790310983270", "cod_dia": "NO_ENCONTRADO",},
  "CHOCOARROZ ALFAJOR DE ARROZ CHO.BLANCO 22GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCOARROZ", "ean": "7790070418289", "cod_dia": "278494",},
  "CHOCOARROZ ALFAJOR DE ARROZ DDL 22 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCOARROZ", "ean": "7790070418203", "cod_dia": "274176",},
  "CHOCOARROZ ALFAJOR FRUTILLA D/ARROZ 22GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCOARROZ", "ean": "7790070416865", "cod_dia": "NO_ENCONTRADO",},
  "CHOCOARROZALFAJOR DE ARROZ C/LIMON 22 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCOARROZ", "ean": "7790070418241", "cod_dia": "NO_ENCONTRADO",},
  "CHOCOARROZALFAJOR DE ARROZ MARROC 22 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "CHOCOARROZ", "ean": "7790070418326", "cod_dia": "NO_ENCONTRADO",},
  "EL CACHAFAZ ALFAJOR MINI CHC SPL 27GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "EL CACHAFAZ", "ean": "77926852", "cod_dia": "307579",},
  "EL CACHAFAZ ALFAJOR NEGRO MOU. 50 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "EL CACHAFAZ", "ean": "77930057", "cod_dia": "305302",},
  "FANTOCHE BLANCO TRIPLE ALFAJOR 80GRS.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "77991584", "cod_dia": "300027",},
  "FANTOCHE DAY EDICION LIMITADA TRIPLE 85 GR ENV 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "7791672000339", "cod_dia": "302559",},
  "FANTOCHE DAY REG SIMPLE 50 GR ENV 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "7791672002074", "cod_dia": "300029",},
  "FANTOCHE SIMPLE NIGHT REGULAR SIMPLE 50 GR PAQ.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "7791672002067", "cod_dia": "300030",},
  "FANTOCHE TRIPLE ALFAJOR 85 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "77991577", "cod_dia": "300028",},
  "FANTOCHE TRIPLE NIGHT ALF.TOR.C/DDL. 85 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "FANTOCHE", "ean": "7791672000247", "cod_dia": "302341",},
  "GEORGALOS FULL MANI SIMPLE ALFAJOR 45 GR 1 UNIDAD": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "GEORGALOS", "ean": "7790380024620", "cod_dia": "NO_ENCONTRADO",},
  "GUAYMALLEN ALFAJOR 38GRS. ALEX VIAN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "GUAYMALLEN", "ean": "77980229", "cod_dia": "267295",},
  "GUAYMALLENBLANCO ALFAJOR 38GRS.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "GUAYMALLEN", "ean": "77980212", "cod_dia": "267294",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "9 DE ORO ALFAJOR SIMPL DDL 45GR 1UN PAQUETE": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7792180145390", "cod_dia": "306946",},
  "9 DE ORO ALFAJOR SIMPL DDL 45GR 1UN PAQUETE": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7792180145406", "cod_dia": "307590",},
  "9 DE ORO ALFAJOR SIMPL DDL 45GR 1UN PAQUETE": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7792180145819", "cod_dia": "NO_ENCONTRADO",},
  "9 DE ORO ALFAJOR SPL 45GR 1UN PAQUETE": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7792180145413", "cod_dia": "NO_ENCONTRADO",},
  "9 DE ORO ALFAJOR SPL 45GR 1UN PAQUETE": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7792180145826", "cod_dia": "NO_ENCONTRADO",},
  "ANIMAL KIND ALFAJOR CHOC VEGANO 50GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7798184451192", "cod_dia": "NO_ENCONTRADO",},
  "ANIMAL KIND ALFAJOR LIMON 42GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7798184451246", "cod_dia": "NO_ENCONTRADO",},
  "ANIMAL KIND ALFAJOR PISTACH 42GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7798184451369", "cod_dia": "NO_ENCONTRADO",},
  "ARBANIT ALFAJOR SPL BAN CHC 50GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "736372567666", "cod_dia": "308240",},
  "FULBITO ALFAJOR 25 GR ARG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77902320", "cod_dia": "289319",},
  "FULBITO ALFAJOR CHOCOLATE 30 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77913586", "cod_dia": "NO_ENCONTRADO",},
  "NEVARES ALFAJOR BLANCO PAQ. 45 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77925626", "cod_dia": "NO_ENCONTRADO",},
  "NEVARES C/DDL ALFAJOR CH.NEGRO 45GR 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77908193", "cod_dia": "NO_ENCONTRADO",},
  "SAN TELMO ALFAJOR BLANCO SPL 35GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77965134", "cod_dia": "NO_ENCONTRADO",},
  "SAN TELMO ALFAJOR NEGRO 60 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7797675001557", "cod_dia": "NO_ENCONTRADO",},
  "SAN TELMO ALFAJOR NEGRO SPL 35GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "77965127", "cod_dia": "NO_ENCONTRADO",},
  "SMACK ALFAJOR MOUSSE 50 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7798094221809", "cod_dia": "NO_ENCONTRADO",},
  "SMACK ALFAJOR NEGRO RELLE.D.D.LEC. 60 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7798094220437", "cod_dia": "NO_ENCONTRADO",},
  "SOL SERRANO ALFAJOR CHOC 40GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7794903232431", "cod_dia": "NO_ENCONTRADO",},
  "SOL SERRANO ALFAJOR D.D/LECHE 40GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "O MARCAS", "ean": "7794903232417", "cod_dia": "NO_ENCONTRADO",},
  "TODDY ALFAJOR MOUSSE SPL 50GR REG PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TODDY", "ean": "7790380023579", "cod_dia": "NO_ENCONTRADO",},
  "TURIMAR ALFAJOR 35 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TURIMAR", "ean": "77909923", "cod_dia": "264665",},
  "TURIMAR TRIPLE BLANCO ALFAJOR 60 GR ARG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TURIMAR", "ean": "77911018", "cod_dia": "NO_ENCONTRADO",},
  "TURIMAR TRIPLE NEGRO ALFAJOR 60 GRARG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "ALFAJORES", "marca": "TURIMAR", "ean": "77910080", "cod_dia": "NO_ENCONTRADO",},
  "BANANITA DOLCA BOMBON BOCAD BANANA 30GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "BANTA-DOLCA", "ean": "77988263", "cod_dia": "298651",},
  "BANANITA DOLCA CHOC 14GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "BANTA-DOLCA", "ean": "77988256", "cod_dia": "300588",},
  "BIZNIKKE NEVADO BIZ.BAN.C/CH.C/LE.Y BLA. 28 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "BIZNIKE", "ean": "77991430", "cod_dia": "110600",},
  "GALLO CHOCONUSS OBLEA ARR.RELL.AVEL.BAN.C/CHO.20 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GALLO", "ean": "7790070416247", "cod_dia": "242671",},
  "GALLO OBLEA D/ARROZ BLACK RELL.BAN. 20GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GALLO", "ean": "7790070431639", "cod_dia": "296755",},
  "GALLO OBLEA D/ARROZ RELL.BAN. CHC 20GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GALLO", "ean": "7790070431905", "cod_dia": "NO_ENCONTRADO",},
  "GALLO OBLEA D/ARROZ WHITE RELL.BAN. 20GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GALLO", "ean": "7790070431653", "cod_dia": "276293",},
  "GALLO OBLEA DE ARROZ RELLE.BAN. 20 GRPAQ.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "GALLO", "ean": "7790070411952", "cod_dia": "205793",},
  "KINDER BUENO BOMBON 21.5 GRX2 U.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KINDER BUENO", "ean": "80052760", "cod_dia": "37004",},
  "KINDER BUENO WHITE REG. BOMBON 19.5 GR X2 PAQ.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KINDER BUENO", "ean": "80761761", "cod_dia": "18373",},
  "KIT KAT CHOCOLATE BLEA BANADA DARK 41.5GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KIT-KAT", "ean": "7891000379073", "cod_dia": "238921",},
  "KIT KAT CHOCOLATE OBLEA BAN TRP CHC 41.5GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KIT-KAT", "ean": "7891000422052", "cod_dia": "NO_ENCONTRADO",},
  "KIT KAT OBLEA BAN.CHOCOLATE C/LECHE 41.5 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KIT-KAT", "ean": "7891000248799", "cod_dia": "148828",},
  "KIT KAT OBLEA.BANADA BCO CHOCOLATE 41.5GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "KIT-KAT", "ean": "7891000379028", "cod_dia": "238922",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "MANTECOL OYG GALL OBLEA BANADA CHC 27GR PAQ 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "MANTECOL", "ean": "7790380026426", "cod_dia": "308808",},
  "NUGATON OBLEA BAN.CHO.C/LEC.PAQ. 27 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "NUGATON", "ean": "7792360072447", "cod_dia": "NO_ENCONTRADO",},
  "NUGATON OBLEA CHOCOLATE BLANCO 27 GRPAQ.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "NUGATON", "ean": "7792360072461", "cod_dia": "245105",},
  "BIG OBLEA BANADA CHC 28GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "O MARCAS", "ean": "7791672014756", "cod_dia": "308242",},
  "NEVARES SMACK CUBA.RELL.MOU.BAN.C/CH. 27 GRPAQ.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "O MARCAS", "ean": "7798094223605", "cod_dia": "NO_ENCONTRADO",},
  "NEVARES SMACK OBLEA BANADA 33 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "O MARCAS", "ean": "7798094220444", "cod_dia": "NO_ENCONTRADO",},
  "SMACK BARRA RELLENA BANADA 35GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "O MARCAS", "ean": "7798094223360", "cod_dia": "295454",},
  "VIZZIO ALMENDRAS BAN CHC O BANADOS 70GR ESTUCHE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "VIZZIO", "ean": "7802215108242", "cod_dia": "104335",},
  "VIZZIO CROCANTE CEREAL BAN.C/CHO. 80 GRCAJA": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BANADOS", "marca": "VIZZIO", "ean": "7792360097983", "cod_dia": "309797",},
  "BIZNIKE CHOCOLATIN BYB CHC PAQUETE 9GR 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "BIZNIKE", "ean": "77992949", "cod_dia": "279379",},
  "EL CACHAFAZ MARROC BOCAD CHC 14GR PAQ 1U REG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "EL CACHAFAZ", "ean": "77985996", "cod_dia": "305303",},
  "FANTOCHE BOCADITO DE DULCE LECHE 28 G PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "FANTOCHE", "ean": "77988102", "cod_dia": "NO_ENCONTRADO",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "NESTLE TAB CHOC SOL BYB 22GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "NESTLE", "ean": "8445291565203", "cod_dia": "131004",},
  "ALFAPAMPA BOCADITO DE CHC 30GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "O MARCAS", "ean": "7798171730101", "cod_dia": "NO_ENCONTRADO",},
  "ALFAPAMPA BOCADITO DE CHC 30GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "O MARCAS", "ean": "7798171733072", "cod_dia": "NO_ENCONTRADO",},
  "INTEGRA BOCADITO CHOCOLATE C/MANI 26GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "O MARCAS", "ean": "7798343751378", "cod_dia": "304507",},
  "NEVARES SMACK BOMBON 16GR PAQ REGULAR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "O MARCAS", "ean": "7798094221793", "cod_dia": "293747",},
  "FERRERO ROCHER BOMBONES 12.5 GRPAQ.X 3 U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "BOMBONES", "marca": "ROCHER", "ean": "78909434", "cod_dia": "23499",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "CONFITURAS", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "BIZNIKKE NEVADO HUEVO DE CHOCO.BLA. 100 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "BIZNIKE", "ean": "7792730019676", "cod_dia": "NO_ENCONTRADO",},
  "BIZNIKKE NEVADO HUEVO DE CHOCOLATE 100 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "BIZNIKE", "ean": "7792730019645", "cod_dia": "NO_ENCONTRADO",},
  "BONAFIDE NUGATON HUEVO DE CHO.NEGRO 177 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "BONAFIDE", "ean": "7792360071945", "cod_dia": "NO_ENCONTRADO",},
  "KINDER GRAN SORPRESA HECHIS HUE.CHO. 150 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER G SORP", "ean": "7898024395706", "cod_dia": "NO_ENCONTRADO",},
  "KINDER GRAN SORPRESA MIXTO SELV/HECHIS 150 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER G SORP", "ean": "8000500020012", "cod_dia": "NO_ENCONTRADO",},
  "KINDER GRAN SORPRESA NATOONS HUE.150 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER GRAN SORPRESA NATOONS", "ean": "7898024396567", "cod_dia": "NO_ENCONTRADO",},
  "KINDER JOY HUEVO DE CHOCOLATE 20 GRC/SORPRESA": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER JOY", "ean": "78602731", "cod_dia": "117941",},
  "KINDER MINI EGGS CHO.C/LEC.RELL.AVEL.BOL. 85 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER MINI EGGS", "ean": "8000500189047", "cod_dia": "NO_ENCONTRADO",},
  "KINDER C/ LECHE P/NENA C/SORP 20 GRS HYF 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER SORPRESA", "ean": "78931053", "cod_dia": "162299",},
  "KINDER C/LECHE P/NENE C/SORP 20 GRS HYF 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "KINDER SORPRESA", "ean": "40084107", "cod_dia": "NO_ENCONTRADO",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "MANTECOL HUEVO CHC. S/SORP 22GR PAS/NAV 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "MANTECOL", "ean": "7790380032038", "cod_dia": "NO_ENCONTRADO",},
  "MANTECOL HUEVO CHOC S/SORP 200GR PAS/NAV 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "MANTECOL", "ean": "7790380032014", "cod_dia": "NO_ENCONTRADO",},
  "FERRERO ROCHER HUEVO DE CHOCOLATE 225 GRPAS/NAV.": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "PASCUAS", "marca": "ROCHER HUEVO CHOCO.", "ean": "7898024397199", "cod_dia": "NO_ENCONTRADO",},
  "GAROTO BATON CHO.C/LEC.TAB.SOLIDA 16 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "BATON", "ean": "7891000441879", "cod_dia": "309179",},
  "BONAFIDE TABLETA CHOCO SOLIDA 30GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "BONAFIDE", "ean": "7792360952657", "cod_dia": "25187",},
  "BONAFIDE TABLETA MANI SOLIDAS 90GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "BONAFIDE", "ean": "7792360097709", "cod_dia": "NO_ENCONTRADO",},
  "GEORGALOS CHOCOLATIN BCO. TAB.SOLIDA 8 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "GEORGALOS", "ean": "77969361", "cod_dia": "NO_ENCONTRADO",},
  "GEORGALOS FULL MANI SOLIDAS 100 GRS PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "GEORGALOS", "ean": "7790380024750", "cod_dia": "NO_ENCONTRADO",},
  "GEORGALOS FULL MANI SOLIDAS 35 GRS PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "GEORGALOS", "ean": "7790380024408", "cod_dia": "NO_ENCONTRADO",},
  "HERSHEY'S 73% DARK TAB.SOLIDA 85GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HERSHEY'S", "ean": "7899970401657", "cod_dia": "NO_ENCONTRADO",},
  "HERSHEY'S CHC SEM AMARG 40% TAB.SOLIDA 82GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HERSHEY'S", "ean": "7899970402838", "cod_dia": "283628",},
  "HERSHEY'S CHC TAB.SOLIDA 82GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HERSHEY'S", "ean": "7899970402814", "cod_dia": "NO_ENCONTRADO",},
  "HERSHEY'S COOKIES & CREAM TABLETA CHC SOLIDA 77GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HERSHEY'S", "ean": "7899970403026", "cod_dia": "224290",},
  "HERSHEY'S TAB AIREADO CHOC C/LECHE 85GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "HERSHEY'S", "ean": "7899970402586", "cod_dia": "NO_ENCONTRADO",},
  "KINDER TAB.SOLIDA 12.5 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "KINDER", "ean": "80050315", "cod_dia": "NO_ENCONTRADO",},
  "M PROPIAS": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "M PROPIAS", "ean": "1", "cod_dia": "NO_ENCONTRADO",},
  "MECANO TUERCA TAB.RELLE. 19 GR": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "MECANO", "ean": "7792360072423", "cod_dia": "NO_ENCONTRADO",},
  "NESTLE CHOCOTRIO CHC RELL C/GALL 90GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "7891000377543", "cod_dia": "295791",},
  "NESTLE CHOCOTRIO CHC RELL C/GALL 90GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "7891000377598", "cod_dia": "295792",},
  "NESTLE CHOCOTRIO CHC RELL C/GALL 90GR PAQUETE 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "7891000377642", "cod_dia": "295790",},
  "NESTLE GALAK SOLIDA 80GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "7891000368626", "cod_dia": "289414",},
  "NESTLE MANI SOLIDAS 33GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "7613287526236", "cod_dia": "NO_ENCONTRADO",},
  "NESTLE TAB CHC SOLIDAS 45GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "8445291565173", "cod_dia": "NO_ENCONTRADO",},
  "NESTLE TAB CHOC SOLIDAS 50GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "8445291565333", "cod_dia": "309155",},
  "NESTLE TAB CHOC SOLIDAS 50GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "8445291565395", "cod_dia": "309177",},
  "NESTLE TAB CHOC. SOLIDAS 25GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "8445291565364", "cod_dia": "308876",},
  "NESTLE TAB CHOC. SOLIDAS 25GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE", "ean": "8445291565425", "cod_dia": "308877",},
  "NESTLE CLASSIC AMARGO TAB.SOLIDA 80GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE CLASSIC", "ean": "7891000368572", "cod_dia": "289456",},
  "NESTLE CLASSIC DIPLOMATA SOLIDAS 80GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE CLASSIC", "ean": "7891000368893", "cod_dia": "289418",},
  "NESTLE CLASSIC TAB.SOLIDA 80GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE CLASSIC", "ean": "7891000369098", "cod_dia": "289455",},
  "NESTLE DUO CLASSIC TAB.SOLIDA 80GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE CLASSIC", "ean": "7891000368992", "cod_dia": "NO_ENCONTRADO",},
  "NESTLE CRUNCH SOLIDA 80GR 1U PAQ": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "NESTLE CRUNCH", "ean": "7891000369371", "cod_dia": "289417",},
  "VAUQUITA TAB. DDL SOLIDA 22GR PAQ 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "O MARCAS", "ean": "77927361", "cod_dia": "NO_ENCONTRADO",},
  "PAULISTA BLANCO TAB.SOLIDA9 GR ARG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "PAULISTA", "ean": "77921239", "cod_dia": "NO_ENCONTRADO",},
  "PAULISTA CHOCOLATE C/LECHE TAB.SOLIDA9 GR ARG": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "PAULISTA", "ean": "77921222", "cod_dia": "NO_ENCONTRADO",},
  "SUFLAIR MILK AIREADO TABLETA 80GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "SUFLAIR", "ean": "7891000329856", "cod_dia": "270391",},
  "TODDY TABLETAS CHC SOLIDA 60GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "TODDY", "ean": "7790380025139", "cod_dia": "NO_ENCONTRADO",},
  "TODDY TABLETAS RELLENAS 60GR PAQUETE 1UN": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "TODDY", "ean": "7790380025115", "cod_dia": "307172",},
  "VIZZIO TAMB CHOCO LECHE Y MANI 165GR 1U": {"empresa": "RESTO", "categoría": "Chocolates", "subcategoría": "TABLETAS", "marca": "VIZZIO", "ean": "7792360094562", "cod_dia": "NO_ENCONTRADO",},
}
